theme: jekyll-theme-minimal
title: atejeda.github.io
description: notes and projects
show_downloads: False

navigation:
  - title: Home
    url: /
  - title: Google Cloud Platform
    url: GoogleCloud
